name: Feature suggestion
description: Suggest a feature
labels: [ "type/enhancement" ]

body:
  - type: checkboxes
    attributes:
      label: Basic Questions
      description: |-
        Please confirm you've gone through the following steps before submitting your feature suggestion.  
        If you believe an item does not apply to your issue, you may check the box regardless.
      options:
        - label: I have checked and confirmed that no similar issues exist, and my issue is not a duplicate (including closed issues).
          required: true
        - label: I have ensured no existing pull requests potentially address my issue.
          required: true

  - type: textarea
    attributes:
      label: Feature description
      description: Please describe the feature and explain why it should be added.
    validations:
      required: true
